# Generated by Django 6.0.2 on 2026-07-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
