# Generated by Django 6.0.2 on 2026-07-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
