# Generated by Django 6.0.2 on 2026-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(help_text='e.g. Full Stack Developer', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(),
        ),
    ]
