# Generated by Django 6.0.2 on 2026-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
    ]
